version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8089:8089"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vue
      - synonyms
  vue:
    build:
      context: ./synonyms-vue
      dockerfile: ./Dockerfile
#    ports:
#      - "8080:8080"

  synonyms:
    build:
      context: ./synonyms-solution
      dockerfile: ./Dockerfile
    image: synonyms
    command: [ "--rm", "-it"]
 
#    ports:
#      - "5000:5000"
    environment:
#      - ASPNETCORE_URLS=http://+5000
#      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_ENVIRONMENT=Production
#    volumes:
#      - ~/synonyms/dev-certs/:/https/