version: '3'
services:
  synonyms:
    image: synonyms
    command: [ "--rm", "-it"]
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ~/synonyms/dev-certs/:/https/